spring:
  application:    name: api_usuarios
  datasource:    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.5:1521/XEPDB1
    password: prueba
    username: prueba
  jpa:    database-platform: org.hibernate.dialect.Oracle8iDialect
    generate-ddl: true
    hibernate:      ddl-auto: update
    show-sql: true
server:  port: 8080
key:
  personas: http://26.30.18.248:8080/persona/dni